#include <stdio.h>

#include "report_exporter.h"


void exportReport(PasswordReport report)
{

    FILE *file;


    file = fopen("CipherKey_Report.txt", "w");


    if(file == NULL)
    {
        printf("Error creating report file!\n");
        return;
    }



    fprintf(file,
    "========================================\n");

    fprintf(file,
    "        CipherKey Security Report\n");

    fprintf(file,
    "========================================\n\n");



    fprintf(file,
    "Password Length : %d\n",
    report.passwordLength);



    fprintf(file,
    "Strength        : %s\n",
    report.strengthLevel);



    fprintf(file,
    "Entropy         : %.2f bits\n",
    report.entropy);



    fprintf(file,
    "Crack Time      : %.2f years\n",
    report.crackTimeYears);



    fprintf(file,
    "Common Password : %s\n",
    report.isCommonPassword ? "YES" : "NO");



    fprintf(file,
    "Keyboard Pattern: %s\n",
    report.hasKeyboardPattern ? 
    "DETECTED" : "NOT DETECTED");



    int score =
        (report.strengthScore * 100) / 6;



    fprintf(file,
    "Security Score  : %d%%\n",
    score);



    fprintf(file,
    "\n========================================\n");

    fprintf(file,
    "Generated by CipherKey v2.0\n");

    fprintf(file,
    "========================================\n");



    fclose(file);



    printf("\nReport exported successfully!\n");

    printf("File: CipherKey_Report.txt\n");

}